task:
  name: "Setting Up tmate"
  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "Sushrut1101"
       - git config --global user.email "guptasushrut@gmail.com"
  
  Storage-Check_script:
       - df -h
       - lsblk
       - ls -lh
  
  SSH-Setup_script:
       - sudo apt install tmate ssh ssh-keygen -y
       - tmate
